<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
        <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>uMedia</RootNamespace>
        <AssemblyName>uMedia</AssemblyName>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <InvariantGlobalization>false</InvariantGlobalization>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets/**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.3" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.3" Condition="'$(Configuration)' == 'Debug'" />
    </ItemGroup>

</Project>
